language: python
python:
  - "3.6"
  - "3.7"

before_install:  
  - mkdir ../solr && pushd ../solr  
  - wget http://archive.apache.org/dist/lucene/solr/7.6.0/solr-7.6.0.tgz  
  - tar xzf solr-7.6.0.tgz && ./solr-7.6.0/bin/solr -c
  - popd
  - ln -s ../solr/solr-7.6.0/bin/solr .

install:
  - pip install pytest coveralls -r requirements.txt

before_script:
  - ./solr zk -upconfig -z localhost:9983 -n tapioca -d configsets/tapioca
  - cp settings_travis.py settings.py

script:
  - coverage run --source=opentapioca --omit="*/tests/*" -m py.test

after_success:
  - coveralls
